export enum CredentialStatusEnum {
  VALIDATE= 'VALIDATE',
  CREDENTIAL_CONNECT_SUCCESS = 'CREDENTIAL_CONNECT_SUCCESS',
  MOVEMENTS_CREATE_START = 'MOVEMENTS_CREATE_START ',
  MOVEMENTS_CREATE_END = 'MOVEMENTS_CREATE_END'
}
